# Configuration for flavours
# https://github.com/Misterio77/flavours
#
# This file should contain a [[items]] section for each application you want themed
# You can also set a shell (outside items) on which to run hooks
# Check flavours repository for more information and examples


# Explanation and default values for keys:

# Through which shell command hooks will run. The command will be replaced in '{}'
shell = "bash -c '{}'"

[[items]]
file = "~/.config/alacritty/alacritty.toml"
template = "alacritty"

[[items]]
file = "~/.config/tmux/tmux.conf"
template = "tmux"
subtemplate = "base16"
hook = 'tmux source-file ~/.config/tmux/tmux.conf'

[[items]]
file = "~/.config/tmux-powerline/themes/default.sh"
template = "tmux-powerline"
subtemplate = "base16"
hook = 'tmux source-file ~/.config/tmux/tmux.conf'
rewrite = true

[[items]]
file = "~/.config/wofi/style.css"
template = "wofi"
rewrite = true

[[items]]
file = "~/.config/nvim/lua/config/theme.lua"
template = "nvim"
subtemplate = "custom"
start = "-- Start Flavours"
end = "-- End Flavours"

[[items]]
file = "~/.config/waybar/style.css"
template = "waybar"
start = "/* Start flavours */"
end = "/* End flavours */"
hook = 'killall waybar; waybar &'

[[items]]
file = "~/.local/themes/firefox-base16.json"
template = "firefox-base16"
hook = "(cd ~/misc/firefox-base16/; bun start -c ~/.local/themes/firefox-base16.json -a -f firefox-developer-edition)"
rewrite = true

[[items]]
file = "~/.config/tridactyl/themes/theme.css"
template = "styles"
subtemplate = "css-variables"
start = "/* Start flavours */"
end = "/* End flavours */"

[[items]]
file = "~/.mozilla/firefox/t1g8shmy.dev-edition-default/chrome/userContent.css"
template = "tridactyl"
start = "/* Start flavours */"
end = "/* End flavours */"

[[items]]
file = "~/.config/mako/config"
template = "mako"
hook = 'killall mako; mako &'
rewrite = true

[[items]]
file = "~/.config/fish/conf.d/fzf.fish"
template = "fzf"
subtemplate = "base16-fish"
rewrite = true

[[items]]
file = "~/.config/ghostty/themes/default"
template = "ghostty"
subtemplate = "custom"
rewrite = true

[[items]]
file = "~/.themes/FlatColor/gtk-3.0/gtk.css"
template = "gtk-flatcolor"
subtemplate = "gtk-3"
start = "/* Start flavours */"
end = "/* End flavours */"

[[items]]
file = "~/.themes/FlatColor/gtk-2.0/gtkrc"
template = "gtk-flatcolor"
subtemplate = "gtk-2"
start = "# Start flavours"
end = "# End flavours"
