# Configuration for flavours
# https://github.com/Misterio77/flavours
#
# This file should contain a [[items]] section for each application you want themed
# You can also set a shell (outside items) on which to run hooks
# Check flavours repository for more information and examples


# Explanation and default values for keys:

# Through which shell command hooks will run. The command will be replaced in '{}'
shell = "bash -c '{}'"

[[items]]
file = "~/.config/alacritty/alacritty.toml"
template = "alacritty"

[[items]]
file = "~/.config/tmux/tmux.conf"
template = "tmux"
subtemplate = "base16"
hook = 'tmux source-file ~/.config/tmux/tmux.conf'

[[items]]
file = "~/.config/wofi/style.css"
template = "wofi"
rewrite = true

[[items]]
file = "~/.config/nvim/lua/hylo/theme.lua"
template = "nvim"
subtemplate = "custom"
start = "-- Start Flavours"
end = "-- End Flavours"

[[items]]
file = "~/.config/waybar/style.css"
template = "waybar"
start = "/* Start flavours */"
end = "/* End flavours */"
hook = 'killall waybar; waybar &'

[[items]]
file = "~/.local/themes/firefox-base16.json"
template = "firefox-base16"
hook = "(cd ~/misc/firefox-base16/; bun start -c ~/.local/themes/firefox-base16.json -a -f firefox-developer-edition)"
rewrite = true

[[items]]
file = "~/.config/tridactyl/themes/theme.css"
template = "styles"
subtemplate = "css-variables"
start = "/* Start flavours */"
end = "/* End flavours */"

[[items]]
file = "~/.mozilla/firefox/t1g8shmy.dev-edition-default/chrome/userContent.css"
template = "tridactyl"
start = "/* Start flavours */"
end = "/* End flavours */"

[[items]]
file = "~/.config/mako/config"
template = "mako"
hook = 'killall mako; mako &'
rewrite = true

#[[items]]
# File to inject to, supports tilde and env var expansion. required
#file = "~/.config/alacritty/alacritty.yml"
# Template to use. required
#template = "alacritty"
# # Subtemplate to use
# subtemplate = "default"
# # If not rewriting, on which line (usually a comment) to start replacing
# start = "# Start flavours"
# # If not rewriting, on which line (usually a comment) to stop replacing
# end = "# End flavours"
# # Should we rewrite the entire file, instead of using the above delimiters?
# rewrite = false
# # Command to execute after injecting (goes through shell)
# hook = ""
# # Whether this hook should be executed when flavours is ran with lightweight flag
# light = true


# Example file. For sway, waybar and (beautiful)discord. Runs hooks through bash:

# shell = "bash -c '{}'"
#
# [[items]]
# file = "~/.config/sway/config"
# template = "sway"
# subtemplate = "colors"
# hook = "swaymsg reload"
# light = false
#
# [[items]]
# file = "~/.config/waybar/colors.css"
# template = "waybar"
# rewrite = true
# 
# [[items]]
# file = "~/.config/beautifuldiscord/style.css"
# template = "styles"
# subtemplate = "css-variables"
# start= "/* Start flavours */"
# end = "/* End flavours */"
