#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor DP-0 -d IV V VI
bspc monitor DP-2 -d I II III
bspc monitor DP-4 -d VII VIII IX

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

feh --bg-fill ~/wallpapers/wallpaper2.jpg
#hsetroot -cover ~/wallpaper/wallpaper1.jpg
fcitx5 -d
picom -b

bspc rule -a Anki desktop=^8 follow=on
#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off
